---
# this file is here to facilitate development/testing
# $ export BUILDKIT_PROGRESS=plain docker compose build
# $ docker compose up -d --build --force-recreate

services:
  # postgres:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password

  backup:
    build:
      context: .
      args:
        ALPINE_VERSION: "3.20"
    env_file:
      - template.env
