---
# this file is here to facilitate development/testing
# $ export BUILDKIT_PROGRESS=plain docker compose build
# $ docker compose up -d --build --force-recreate

services:
  postgres:
    container_name: postgres-backup-test
    image: postgres:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - postgres.env

  backup:
    container_name: cron-remote-backup-test
    image: rizl4s/postgres-backup-owncloud:latest
    build:
      context: .
      args:
        ALPINE_VERSION: "3.20"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - TZ=UTC
    env_file:
      - pgbackups.env
      - postgres.env
